server {
    listen 80;
    server_name YOUR_SERVER_IP_OR_DOMAIN; # 请替换为你的服务器IP或域名

    # 日志配置
    # access_log  /var/log/nginx/host.access.log  main;

    # url匹配
    location / {
        # root   /usr/share/nginx/html;
        # index home.html;
        proxy_pass   http://localhost:8080; # 请更新为你的Django服务地址
        proxy_redirect default;
        proxy_http_version 1.1;
        proxy_connect_timeout   60;
        proxy_send_timeout      60;
        proxy_read_timeout      90;
    }
    location /home/ {
        proxy_pass   http://localhost:8080/home/;
        proxy_redirect default;
        proxy_http_version 1.1;
        proxy_connect_timeout   60;
        proxy_send_timeout      60;
        proxy_read_timeout      90;
    }
    location /jsonvim/ {
        proxy_pass   http://localhost:8080/jsonvim/;
        proxy_redirect default;
        proxy_http_version 1.1;
        proxy_connect_timeout   60;
        proxy_send_timeout      60;
        proxy_read_timeout      90;

        # 应用于特定server块的配置
        client_max_body_size 5M;
        client_body_buffer_size 5M;
        fastcgi_buffers 4 5M;
        fastcgi_buffer_size 5M;
    }
    location /static/ {
        alias /path/to/AIdrawG/staticfiles/;  # 静态文件在本地的存储绝对路径，请替换为实际路径
        autoindex off; # 禁止目录浏览
        valid_referers none blocked server_names YOUR_DOMAIN; # 请替换为你的域名
        if ($invalid_referer) {
            return 403; # 如果不是来自允许的域名，则返回403错误
        }
    }
    location /data/ {
        alias /path/to/data/;  # 请替换为实际的数据目录路径
        autoindex off; 
        valid_referers none blocked server_names YOUR_DOMAIN; # 请替换为你的域名
        if ($invalid_referer) {
            return 403; 
        }
    }
    
    location /test/ {
        proxy_pass   http://localhost:8080/test/;
        proxy_redirect default;
        proxy_http_version 1.1;
        proxy_connect_timeout   60;
        proxy_send_timeout      60;
        proxy_read_timeout      90;
    }

}
